### ISSUE TITLE
Missing libs in most recent image

### ISSUE THREAD

**Issue by maxcountryman** [instrumentisto/geckodriver-docker-image#11]
I've recently started seeing the following errors with the latest image:

```
geckodriver  | *** You are running in headless mode.
geckodriver  | console.warn: services.settings: Ignoring preference override of remote settings server
geckodriver  | console.warn: services.settings: Allow by setting MOZ_REMOTE_SETTINGS_DEVTOOLS=1 in the environment
geckodriver  | [GFX1-]: glxtest: libpci missing
geckodriver  | [GFX1-]: glxtest: libGL.so.1 missing
geckodriver  | [GFX1-]: No GPUs detected via PCI
geckodriver  |
geckodriver  | 1717000205057    Marionette      INFO    Marionette enabled
geckodriver  | 1717000205299    Marionette      INFO    Listening on port 34131
geckodriver  | Read port: 34131
geckodriver  | [GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
geckodriver  | console.error: ({})
```

**Comment by tyranron** [comment]
@maxcountryman could you specify the command you're running the image with?

**Comment by maxcountryman** [comment]
@tyranron `docker run -it -p 4444:4444 instrumentisto/geckodriver`

**Comment by tyranron** [comment]
@maxcountryman anything else to reproduce the issue? I have the following:
```bash
$ docker run --rm -it -p 4444:4444 docker.io/instrumentisto/geckodriver:126.0-driver0.34.0-r0 
Unable to find image 'instrumentisto/geckodriver:126.0-driver0.34.0-r0' locally
126.0-driver0.34.0-r0: Pulling from instrumentisto/geckodriver
09f376ebb190: Already exists 
79f518476e83: Pull complete 
Digest: sha256:6e8fb1d6fdbdf30402c18df86089c901e43e0ca6b31ef58cbd9e6c1ef7fc39c8
Status: Downloaded newer image for instrumentisto/geckodriver:126.0-driver0.34.0-r0
1717088605639   geckodriver     INFO    Listening on 127.0.0.1:4444
```

**Comment by tyranron** [comment]
@maxcountryman ok, I was able to reproduce the issue. Strangely, despite the errors written into logs they don't affect any use cases of our WebDriver usage and all our builds/tests are OK.

**Comment by tyranron** [comment]
@maxcountryman we install [all the dependencies of `firefox-esr` Debian package](https://github.com/instrumentisto/geckodriver-docker-image/blob/126.0.1-driver0.34.0-r0/Dockerfile#L24), since Debian doesn't have a package for non-ESR Firefox, and as the versions of ESR and non-ESR may differ quite much, such problems may happen.

I've [added these libs](https://github.com/instrumentisto/geckodriver-docker-image/commit/53bbf28778a5129a3da4745913086a6916970c4b#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R24), so try out the `126.0.1-driver0.34.0-r1` image version. I've tested it in our pipelines and the error has gone.

The worst part, I don't know how to build a test to catch such regressions in the future. If you have any ideas in mind, PR is welcome.

**Comment by maxcountryman** [comment]
Thanks for this. I'll give it a try shortly.
